[Project]
author = "Mustafif Khan"
title = "MKProject Books Plan"
date = "Version 1.0"
project_name = "Plan"
template = "Basic" #Make sure to have first letter upercased

[Document]
paper_size = "letterpaper"
font_size = 11 #font size number
document_class = "article"
packages = ["", ""]
